openapi: 3.0.0

paths:
  /pets:
    get:
      summary: This endpoint return a list of pets in adoptions.
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getPets/invocations"
        httpMethod: "POST"
        
  
  /pets/{petId}:
    put:
      summary: This endpoint is for updating a pet in db
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                healt_status:
                  type: string
                age:
                  type: string
                location:
                  type: string
                pictures:
                  type: array
                  properties:
                    items:
                      type: string
      parameters:
        - name: petId
          in: path
          required: true
          description: Pet unique id.
          schema:
            type : integer
            format: int64
            minimum: 1
        - name: type
          in: query
          required: true
          description: Pet type
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:updatePet/invocations"
        httpMethod: "POST"
        

# // SOLICIT // # 

 /pets/solicitAdoption/{adoptID}:
    put:
      summary: This endpoint solicits an adoption (creates a topic with the email and saves it on dynamodb)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                adopted:
                  type: boolean
                email:
                  type: string
      parameters:
        - name: adoptID
          in: path
          required: true
          description: Adoption ID
          schema:
            type : integer
            format: int64
            minimum: 1
        - name: email
          in: query
          required: true
          description: email for the adoption
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:solicitAdoption/invocations"
        httpMethod: "POST"

# // APPROVAL// #   

  /pets/approveAdoption/{adoptID}:
    put:
      summary: This endpoint aproves an adoption by changing Adopted from false to true
      parameters:
        - name: adoptID
          in: path
          required: true
          description: Adoption ID
          schema:
            type : string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:approveAdoption/invocations"
        httpMethod: "POST"