AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
    
Description: Adoption CloudFormation Project
Resources:
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: adopt
      Handler: lambda.handler
      Runtime: python3.6
      CodeUri: package/
      Policies:
       - DynamoDBReadPolicy:
          TableName: !Ref MyTable
      # Role: !GetAtt MyLambdaRole.Arn
      Environment:
        Variables:
          ADOPTION_TABLE: !Ref MyTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/pets"
            Method: GET
                      
  SolicitAdoption:
    
  AdoptCheck:
  
  SendEmail:
  
  
  
#  MyLambdaRole:
#    Type: AWS::IAM::Role
#    Properties:
#      RoleName: husky